# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 30
verbose: true

script:
  - command: "/usr/bin/bash /usr/local/libexec/kaskados-apply-user-preferences ${ROOT} ${USER} ${gs[kaskadBrightness]} ${gs[kaskadWarmLight]}"
    timeout: 30

i18n:
  name: "Saving display preferences"
  name[ru]: "Сохранение настроек экрана"
